### PR TITLE
Adding batch option to top

### PR DESCRIPTION
**Pull request by boscard**
This change enables batch option in top which is designed for example for saving output to file.

### CODE REVIEW

**Comment by iynere** [comment]
thank you ! @boscard

**Comment by iynere** [comment]
@boscard hey, so sorry, i realized we actually ported all the commands here to a different orb: https://github.com/CircleCI-Public/build-tools-orb/tree/master/src/commands

i'll make this same change there—going to disable this repo & hide this orb. please use `build-tools` going forward ! thank you!

**Comment by boscard** [comment]
@iynere Thanks for info. I'll switch to that orb soon :)

**Comment by iynere** [comment]
perfect. hiding the orb won't stop it from working, so you'll be fine.

**Pull request merged**
